### ISSUE TITLE
Issue with tickets created via Facebook Channel

### ISSUE THREAD

**Issue by KevinJosephMorin** [mozts2005/ZendeskApi_v2#108]
I am using your dll for a whole bunch of ZenDesk queries.  It is truly fantastic.

I recently enabled the Facebook Channel in ZenDesk.

I found today in my code logs that any Facebook created tickets fail with the following lines of code:
Dim objAPI As New ZendeskApi("https://<companyname>.zendesk.com/api/v2", "<username>", "<password>")

Dim objTicketAuditLookup As GroupAuditResponse = objAPI.Tickets.GetAudits(pintZDTicketId)

I have looked at the JSON string that is returned and it looks okay.

I have found that every Facebook post fails.  Perhaps it is a reserved character in all my posts or perhaps it is something about the Facebook Channel markup.

The error I am getting is: "Error reading string. Unexpected token: StartObject. Path 'audits[0].events[0].data', line 1, position 836.    at Newtonsoft.Json.JsonReader.ReadAsStringInternal()"

I upgraded my DLL to the one from two weeks ago and it didn't solve the problem.

**Comment by mozts2005** [comment]
If you could please send a example of your code in I would love to try and help you.
