### ISSUE TITLE
Bundled version is out-of-date

### ISSUE THREAD

**Issue by joerick** [mozts2005/ZendeskApi_v2#119]
Hi @eneifert,

Thanks for the library! It's very useful. 

I just wanted to highlight a problem I came across in case others might be caught by it.

Initially I tried using the library by using the assembly at https://github.com/eneifert/ZendeskApi_v2/tree/master/lib/net45 , but I quickly ran into bugs that matched solved issues on the issue tracker. Took me a little while to realise I was using an out-of-date version of the library. Compiling a new assembly from source solved the problem.

Is there a reason there's an out-of-date bundled version? Can they be removed from the repository?

Joe

**Comment by mozts2005** [comment]
This file will be removed. 
 Please use Nuget. For that latest version 
https://www.nuget.org/packages/ZendeskApi_v2/
