### ISSUE TITLE
Problem when trying to update a ticket with custom fields

### ISSUE THREAD

**Issue by lottev92** [mozts2005/ZendeskApi_v2#122]
Hi all,

Today i was trying to update a ticket using your API wrapper, but i'm getting the following error on some tickets (NOTE: not all tickets give this error):

The remote server returned an error: (422) Unprocessable Entity. Connection: keep-alive
Status: 422 Unprocessable Entity
X-Zendesk-API-Version: v2
X-Zendesk-API-Warn: Removed restricted keys ["has_incidents", "created_at", "updated_at"] from parameters according to whitelist
X-Frame-Options: SAMEORIGIN
X-Zendesk-Origin-Server: app5.pod5.iad1.zdsys.com
X-UA-Compatible: IE=Edge,chrome=1
X-Request-Id: 98d3d1e70b9183cba3af0f46e5c08eef
X-Runtime: 0.134050
X-Rack-Cache: invalidate, pass
X-Zendesk-Request-Id: 1803ef3b4548a9094e30
Content-Length: 145
Cache-Control: no-cache
Content-Type: application/json; charset=UTF-8
Date: Tue, 17 Feb 2015 09:22:45 GMT
Server: nginx

Any suggestions?

Kind regards,
Lotte

**Comment by mattavidhyasagarreddy** [comment]
Even i too faced the same, API warning me: "Removed restricted keys ["created_at"] from parameters according to whitelist". But later, it started working. No sure why this is happening. It's working for me against custom fields & actual fields too. :+1:

**Comment by mozts2005** [comment]
Please Let me know if this is still an issue for you.
 If you can please provide a example of your code that will help.

**Comment by gkgourav45** [comment]
I m still getting same error 
curl https://{subdomain}/api/v2/users/{userid}.json   -H "Content-Type: application/json" -X PUT -d '{"user_field":{"mycustomfield": "myvalue"}}'     -v -u {emailid}:{password}
tried with
curl https://{subdomain}/api/v2/users/{userid}.json   -H "Content-Type: application/json" -X PUT -d '{"user_fields":{"mycustomfield": "myvalue"}}'     -v -u {emailid}:{password}
but still no luck. i am using admin credential to update custom user field of agent. custom user field is of type text.

**Comment by mozts2005** [comment]
Please show an example using C# or better yet create a failing test case as a pull request.
