### ISSUE TITLE
Support OrganizationMembership API

### ISSUE THREAD

**Issue by KevinJosephMorin** [mozts2005/ZendeskApi_v2#124]
ZenDesk is releasing a way to assign a user to multiple orgs.  It has been in a beta for two years.  Here is the new API functionality explained.  https://support.zendesk.com/hc/communities/public/posts/203464106-Managing-Organization-Memberships-via-the-Zendesk-API

**Comment by mozts2005** [comment]
Looks good to me. 

If someone is able feel free to jump in here. I will add this to our road map

**Comment by CKCobra** [comment]
This might be able to be closed.  The organization memberships was added with #152.
