### ISSUE TITLE
Search API - limit number of results returned

### ISSUE THREAD

**Issue by michaelalex** [mozts2005/ZendeskApi_v2#135]
Hi,

I'm using the Search API to query and return unsolved tickets by requester email address. However there isn't anyway of setting the number of tickets returned to something smaller than 100. Would you be open to extending the search methods within the Search/ISearch class/interface to accept page size as an additional parameter. Zendesk API allows an extra querystring parameter called "per_page" to be appended onto the url.

Thanks,

Michael

**Comment by mozts2005** [comment]
I would be very much open to adding this. looks as you know what needs to be done. Please add a pull request.

**Comment by mattnis** [comment]
I believe this was implemented with pull request #179
