### ISSUE TITLE
release v2 3.0.21

### ISSUE THREAD

**Issue by artfulhacker** [mozts2005/ZendeskApi_v2#137]
I see the package updated in Nuget but what changes did this include? I don't see anything in GitHub for 12+ days....

https://www.nuget.org/packages/ZendeskApi_v2/3.0.21

**Comment by mozts2005** [comment]
if you look at [appveyor](https://ci.appveyor.com/project/mozts2005/zendeskapi-v2/history) 
this build is for commit [dc0591378](https://github.com/mozts2005/ZendeskApi_v2/commit/dc0591378563caaab0cd8b841429c7d349f0162c)

it looks as if nuget was down at the time of the commit. so when I ran the build again everything published.
