### ISSUE TITLE
from 3.0.20 to 3.0.29 getting Unauthorized message

### ISSUE THREAD

**Issue by artfulhacker** [mozts2005/ZendeskApi_v2#139]
Using 3.0.20 with no issues, update to 3.0.29 and now I get:

System.Net.WebException : The remote server returned an error: (401) Unauthorized. Connection: keep-alive

Test Name:	TestZenApi
Test Outcome:	Failed
Test Duration:	0:00:00.494

Result Message:	
System.Net.WebException : The remote server returned an error: (401) Unauthorized. Connection: keep-alive
Status: 401 Unauthorized
Content-Type: application/json
Server: nginx
WWW-Authenticate: Bearer realm="Zendesk::OAuth Bearer Token Authentication", error="invalid_token", error_description="The access token provided is expired, revoked, malformed or invalid for other reasons."

**Comment by artfulhacker** [comment]
I used package manager to downgrade and it works perfectly

Uninstall-Package ZendeskApi_v2 -Force
Install-Package ZendeskApi_v2 -Version 3.0.20.0

**Comment by mozts2005** [comment]
I think you want to use the new constructor for oauth.

https://github.com/mozts2005/ZendeskApi_v2/blob/master/ZendeskApi_v2/ZendeskApi.cs#L72
 
If this does not work can you please summit a test case so that we can try and if this.
