### ISSUE TITLE
User Custom Field of DateTime type

### ISSUE THREAD

**Issue by larriant** [mozts2005/ZendeskApi_v2#140]
Hello,

I am trying to add a Custom Field with a DateTime type to Users. Is this possible?

I'm looking for something like this: user.CustomFields.Add("datecreated", DateTimeOffset.Parse(output[i]))

Thanks

**Comment by larriant** [comment]
Also I am having trouble creating a custom field with a Date time:
ticket.CustomFields.Add(new CustomField() {Id = 26720341, Value =DateTimeOffset.Parse("8/14/2015 11:56:35 AM") });

**Comment by mozts2005** [comment]
Please submit a code sample or unit test

**Comment by mozts2005** [comment]
closing Issue as there has been no response to questions asked.
