### ISSUE TITLE
Ticket Side-Loading

### ISSUE THREAD

**Issue by mattnis** [mozts2005/ZendeskApi_v2#143]
I would like to be able to specify Side-Loading of Users, Organizations, etc when getting Tickets.
I have the code already implemented and could provide it.

**Comment by mozts2005** [comment]
I you have it now. I am more then happy to add it to the project just submit a pull request.

**Comment by mattnis** [comment]
I created another pull request.

Thank you.

On Thursday, August 20, 2015, Elizabeth Schneider <notifications@github.com>
wrote:

> Closed #143 <https://github.com/mozts2005/ZendeskApi_v2/issues/143> via
> 99edc10
> <https://github.com/mozts2005/ZendeskApi_v2/commit/99edc10a3d4fd2779339d05b89e1648295afeb7a>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozts2005/ZendeskApi_v2/issues/143#event-387856455>.
>


-- 
-Matt-
