### ISSUE TITLE
Can't update user with boolean custom field

### ISSUE THREAD

**Issue by BernhardGa** [mozts2005/ZendeskApi_v2#157]
Hi,

I added a Boolean custom field to the user.
After that I can't no longer update users. No matter if I changed the custom field or not.

The error I got from the API is:
Status: 422 Unprocessable Entity
X-Zendesk-API-Version: v2
X-Zendesk-API-Warn: Removed restricted keys ["url", "created_at", "updated_at", "active", "shared", "last_login_at"] 
from parameters according to whitelist

After removing the Boolean field everything was OK.
It seems that only custom fields of string can be processed via this API.

Best regards,
Bernhard

**Comment by mozts2005** [comment]
Would you please create a pull request will a unit test showing the issue

**Comment by mattnis** [comment]
I was able to reproduce this.  When a user is retrieved, it will contain a
dictionary with values like True or False.
If your scenario is that you want to change some other field and then save
the user, then the custom fields collection will be sent with these True or
False values.
It seems that ZenDesk doesn't like these values and returns an error.
I tested that it Works if you change the values to 1 or 0  (code below).
We shouldn't have to modify existing values as they come from the api.
Maybe the dictionary should be <string, object> ?  Need to test some more.

var user = api.Users.GetAllUsers().Users[0];
user.CustomFields["checkbox"] = 0.ToString();
api.Users.UpdateUser(user);

-Matt-

**Comment by mattnis** [comment]
I just tested this:

[JsonProperty("user_fields")]
public IDictionary<string, string> CustomFields { get; set; }

Change to:

[JsonProperty("user_fields")]
public IDictionary<string, object> CustomFields { get; set; }

Everything works.
Saving User, saving custom field values.

But this may be a breaking change.
Any way to configure json to get around this?

thanks


-Matt-

**Comment by BernhardGa** [comment]
I looked into the different CustomFields in Tickets, Users & Organizations

At the Tickets a separate class with a Object as the value property:
[JsonProperty("custom_fields")]
public IList<CustomField> CustomFields { get; set; }

namespace ZendeskApi_v2.Models.Tickets
{
    public class CustomField
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("value")]        
        public object Value { get; set; }
    }    
}

In Organization and User the CustomFields are defined as: 
public IDictionary<string, string> CustomFields { get; set; }

Wouldn't it better to move the CustomField from Ticket to Shared and use it also in Organization and User?

**Comment by NJain27** [comment]
Same for me - changed the boolean to 1 or 0 and not getting the 422 unprocessable entity error anymore.
