### ISSUE TITLE
Missing fields formatted_phone & phone in Ticket.Via.Source.To & .From

### ISSUE THREAD

**Issue by BernhardGa** [mozts2005/ZendeskApi_v2#158]
In case a ticket is created via a phone call ( Ticket.Via.Channel = 'Voice') the From an To has two more fields: formatted_phone & phone

"source": {
        "rel": "voicemail",
        "from": {
          "formatted_phone": "+49 89 555 666777",
          "phone": "+4989555666777",
          "name": "Caller +49 89 555 666777"
        },
        "to": {
          "formatted_phone": "+49 89 666 777888",
          "phone": "+4989666777888",
          "name": "support phone"
        }
      }

**Comment by mozts2005** [comment]
closed by #181
