### ISSUE TITLE
Support Sideloading with Ticket Comments

### ISSUE THREAD

**Issue by BrentBrehm** [mozts2005/ZendeskApi_v2#162]
The current GetTicketComments doesn't support sideloading. Would need to add sideloading option and add users to the GroupCommentResponse.

**Comment by mattnis** [comment]
Do ticket comments support side-loading?
The api documentation is not very clear.  It has the Ticket endpoint, but
not the Ticket Comments endpoing.  These two are listed separately in the
left navigation bar.
https://developer.zendesk.com/rest_api/docs/core/side_loading


-Matt-

**Comment by BrentBrehm** [comment]
I wondered the same thing when I looked at the documentation. It isn't listed specifically (they may be including it under tickets?) but adding the include option to the request works. I have verified that it works for users because that it was I was specifically looking for.

https://{subdomain}.zendesk.com/api/v2/tickets/{ticketid}/comments.json?include=users

**Comment by mozts2005** [comment]
Closed by #173
