### ISSUE TITLE
Async methods rasie AggregateException instead of the actual exception

### ISSUE THREAD

**Issue by dcrowe** [mozts2005/ZendeskApi_v2#165]
Hi, 
I'm calling api.Tickets.CreateTicketAsync with incorrect credentials and am getting an AggregateException instead of the expected WebException. It looks like there are some calls to Task.Wait() in the RunRequestAsync(...) method which are causing the incorrect exception to be passed back to the user.

**Comment by dcrowe** [comment]
I'm also getting a null ptr error if the ZenDesk cannot be contacted. (We've got some pretty poor internet here at work...)

**Comment by mozts2005** [comment]
Closed by pull request #167
