### ISSUE TITLE
Implement show_many endpoint for Users

### ISSUE THREAD

**Issue by mattnis** [mozts2005/ZendeskApi_v2#170]
https://developer.zendesk.com/rest_api/docs/core/users#show-many-users

Since the Search api doesn't allow side-loading, I need to load user information for all results of Ticket search.   This would be best done in one call, sending a list of user ids that were found in ticket results.

We should either implement all endpoints right away or create a more generic solution (like be able to pass in an endpoint by string).

**Comment by mozts2005** [comment]
Closed by #173
