### ISSUE TITLE
 GetAllUsers fails with 401 Unauthorized 

### ISSUE THREAD

**Issue by KenBilling** [mozts2005/ZendeskApi_v2#187]
My code calling GetAllUsers fails with 401 Unauthorized at zendesk.com/api/v2/users.json using the same credentials that succeed with CURL. Updated to 3.2.14 but it doesn't help.

Any advice?

**Comment by mozts2005** [comment]
can you create a pull request with a unit test showing the issue. we have credentials in the testing project that can be used.

**Comment by KenBilling** [comment]
I found the cause in my code. The API token was getting converted to all lower case.
