### ISSUE TITLE
Get Ticket by Custom Field Value Too Slow

### ISSUE THREAD

**Issue by bhardister** [mozts2005/ZendeskApi_v2#188]
Hi, I need to retrieve a ticket(s) for a specific custom field where ID = x that have a specific value. It's likely that the tickets will be recent so I'm pulling the tickets in descending order and looking for the match. However, the performance is very slow (~ 6 up to 30 sec).

Here's the code. Can you suggest a way to do this that will return more quickly the results?

<pre class="csharpcode">
[TestMethod]
<span class="kwrd">public</span> <span class="kwrd">void</span> GetTicketByTfsId() {
    <span class="kwrd">var</span> tfsCustomField = api.Tickets.GetTicketFields().TicketFields.FirstOrDefault(f =&gt; f.Title == <span class="str">"TFS #"</span>);
    Debug.Assert(tfsCustomField != <span class="kwrd">null</span>, <span class="str">"tfsCustomField != null"</span>);
    <span class="kwrd">var</span> tfsFieldId = tfsCustomField.Id;
    Assert.AreEqual(TfsNumberCustomFieldId, tfsFieldId);

    <span class="kwrd">var</span> page = <span class="kwrd">new</span> GroupTicketResponse();
    <span class="kwrd">var</span> tfsTicket = <span class="kwrd">new</span> Ticket();
    <span class="kwrd">var</span> totalPages = api.Tickets.GetAllTickets().TotalPages;
    <span class="kwrd">for</span> (<span class="kwrd">var</span> i = totalPages; i &gt; 0; i--) {
        page = api.Tickets.GetAllTickets(page: i);
        <span class="kwrd">foreach</span>(<span class="kwrd">var</span> ticket <span class="kwrd">in</span> <span class="kwrd">from</span> ticket <span class="kwrd">in</span> page.Tickets let ticketTfsCustomField = ticket.CustomFields.Select(s =&gt; s).SingleOrDefault(w =&gt; w.Id == tfsFieldId)
        where ticketTfsCustomField != <span class="kwrd">null</span> where ticketTfsCustomField.Id == TfsNumberCustomFieldId
        where ticketTfsCustomField.Value != <span class="kwrd">null</span> where!<span class="kwrd">string</span>.IsNullOrWhiteSpace(ticketTfsCustomField.Value.ToString())
        where ticketTfsCustomField.Value.ToString() == SampleTicketTfsNumber select ticket) {
            tfsTicket = ticket;
            i = 0;
        }
    }
    Assert.AreEqual(SampleTicketId, tfsTicket.Id);
}</pre>

**Comment by mozts2005** [comment]
I see a few issues with your code. but I think what you want to try is using the search api 

I have not found anything in the docs about searching for a given value for a given custom field so that filter will still have to happen on the client and not the server but have look at this. 
```C#
[Test]
        public void GetTicketByTfsId()
        {
            long TfsNumberCustomFieldId = Settings.CustomFieldId;
            int SampleTicketId = 5031;
            string SampleTicketTfsNumber = "Test";
            string searchString = "fieldvalue:Test";

            var searchResult = api.Search.SearchFor<Ticket>(searchString);

            var tfsTicket = searchResult.Results.FirstOrDefault(t =>
            t.CustomFields.FirstOrDefault(c => c.Id == TfsNumberCustomFieldId
            && ((string)c.Value) == SampleTicketTfsNumber) != null);

            Assert.AreEqual(SampleTicketId, tfsTicket.Id);
        } 
```

https://developer.zendesk.com/rest_api/docs/core/search

**Comment by bhardister** [comment]
Wow, yes, that works much better. I'm getting a result in about 1 second. Thanks so much!
