### ISSUE TITLE
Help Center CreateSection API endpoint not correct, cannot create new sections.

### ISSUE THREAD

**Issue by Marcus10110** [mozts2005/ZendeskApi_v2#195]
I'm trying to use the help center create section call to create a new section for a specific category, using this call:
api.HelpCenter.Sections.CreateSection

However, I get this error:
The remote server returned an error: (404) Not Found.Error content: {"error":"InvalidEndpoint","description":"Not found"} 

looking at this source file:
ZendeskApi_v2/Requests/HelpCenter/Sections.cs

It looks like it's trying to use this endpoint:
"help_center/sections.json"

The API documentation for this is here:
https://developer.zendesk.com/rest_api/docs/help_center/sections#create-section

and shows these two endpoints for create section:
POST /api/v2/help_center/categories/{id}/sections.json
POST /api/v2/help_center/{locale}/categories/{id}/sections.json

**Comment by mozts2005** [comment]
Can I get you to submit a unit test to allow us to fix this issue faster

**Comment by KenBilling** [comment]
I'm running into the same problem.

**Comment by Marcus10110** [comment]
#216 Submitted pull request with unit test and fix.
