### ISSUE TITLE
Search function returns NULL value

### ISSUE THREAD

**Issue by jehanzebafridi** [mozts2005/ZendeskApi_v2#196]
Hi,

I am trying to get tickets in a specific date range and I am using Zendesk Search API. However, the search function always returns NULL. Following is my statement. 
GroupTicketResponse tickets = api.Search.GetByPageUrl<GroupTicketResponse>("https://testdomain.zendesk.com/api/v2/search.json?query=type:ticket created>2016-01-01 created<2016-01-13");

Please help in this regard.

Thanks,
Jehan

**Comment by yyuc** [comment]
Try to use the <b>SearchResult<T></b> instead of <b>GroupTicketResponse</b>.
SearchResults<Ticket> tickets = api.Search.GetByPageUrl<SearchResults<Ticket>>("https://testdomain.zendesk.com/api/v2/search.json?query=type:ticket created>2016-01-01 created<2016-01-13");
