### ISSUE TITLE
Article search serialization error  (when Author Id exceeds max int).

### ISSUE THREAD

**Issue by TPMcMahon** [mozts2005/ZendeskApi_v2#203]
The Result class should define Id, AuthorId and SecionId as long? (or maybe long), just as they are defined in Article.

var results = api.Articles.SearchArticlesFor("Test article");

"An unhandled exception of type 'Newtonsoft.Json.JsonReaderException' occurred in Newtonsoft.Json.dll

Additional information: JSON integer **4303108328** is too large or small for an Int32. Path 'results[0].author_id', line 1, position 244."

**Comment by mozts2005** [comment]
commit  ecb8461 has fixed this issue. closing this issue
