### ISSUE TITLE
GetUserIdentities serialization error ( JSON integer is too large or small for an Int32)

### ISSUE THREAD

**Issue by alexvilper** [mozts2005/ZendeskApi_v2#205]
It seems that the UserId in the UserIdentity class should be defined as **long** instead of **int**, the same way the Id is defined as **long** in the User class :

```
public class UserIdentity
    {

        [JsonProperty("id")]
        public long? Id { get; set; }

        [JsonProperty("user_id")]
        public int UserId { get; set; }
     
    .....

public class User
    {
        [JsonProperty("id")]
        public long? Id { get; set; }
    ....

```
The following error is being generated:

`_zdApi.Users.GetUserIdentities((long)user.Id);`

Newtonsoft.Json.JsonReaderException: JSON integer **3539580668** is too large or small for an Int32. Path 'identities[0].user_id', line 1, position 136.

**Comment by bvillanueva-mdsol** [comment]
Hi Zendesk team, we also have encountered this issue when getting Articles. Author_id was not able to handle a long value. Is there any updates on the fix for this? Thanks

**Comment by mozts2005** [comment]
give the latest

**Comment by mozts2005** [comment]
Given that I have not received feedback I am closing the issue.
