### ISSUE TITLE
Ticket comment needs to have  HTML body added

### ISSUE THREAD

**Issue by mozts2005** [mozts2005/ZendeskApi_v2#208]
Zendesk api calls for a read/write string property for html_body 

https://developer.zendesk.com/rest_api/docs/core/ticket_comments

issue was originally proposed by  @avmesquita

**Comment by mozts2005** [comment]
Current docs call for read only string property which is currently in the client. Closing story

**Comment by yonahs** [comment]
I see that this is updated in the Source code here, but the version I got from Nuget 3.6.1 had it set to Private still.
I recompiled the source here and it worked.

Otherwise, I saw all the html tags in the ticket

**Comment by mozts2005** [comment]
Yes this code has not been released yet. You can find a testing build on the myget feed. https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2

**Comment by yonahs** [comment]
Is it dangerous that I am using the source code from here?

**Comment by mozts2005** [comment]
No more dangerous, then using any other open source code. You should have your security team evaluate the code or run a scan with [WhiteSource](https://marketplace.visualstudio.com/items?itemName=whitesource.ws-bolt). if you find any issue please report them.
