### ISSUE TITLE
TicketExportResponse - EndDate property not serialized correctly

### ISSUE THREAD

**Issue by PureItTech** [mozts2005/ZendeskApi_v2#209]
When calling a method that returns a TicketExportResponse (i.e. Tickets.GetIncrementalTicketExport()), then "EndDate" parameter returns a raw Json / Enoch date rather than properly serializing it the way other dates are returned.

To fix this, you simply need to add the "[JsonConverter(typeof(IsoDateTimeConverter))]" attribute to the "EndDate" parameter of the "TicketExportResponse class.

**Comment by mozts2005** [comment]
I am unable to find the issue can you submit a test case with example code

**Comment by PureItTech** [comment]
Sorry for the delay ... here is some test code to show you what I'm talking about:

        public static string ListZendeskRecentTickets(DateTime startTime)
        {
            try
            {
                var utcStartTime = startTime.ToUniversalTime();
                var resp = ZD.Tickets.GetIncrementalTicketExport(utcStartTime);
                var tickets = resp.Results;

                //THIS SHOULD NOT BE NECESSARY
                //Note: the "fromUnixTime()" is a helper method I use
                var endDateTime = resp.EndTime.fromUnixTime().ToLocalTime();

                var ticketList = String.Join(CRLF, tickets.Select(t =>
                    $"Ticket {t.Id} updated at {t.UpdatedAt:G}, Status: {t.Status}"));
                var result = $"Found {tickets.Count} recent tickets as of {endDateTime:G}.\r\n{ticketList}";
                return result;
            }
            catch (WebException ex)
            {
                return ex.InnerException.Message;
            }
        }

**Comment by mozts2005** [comment]
Closing as this has been fixed
