### ISSUE TITLE
(401) Unauthorized "error":"invalid_token"

### ISSUE THREAD

**Issue by aliparlar** [mozts2005/ZendeskApi_v2#214]
Hello,

I managed to get the API to work by using email&password authentication. I am trying to switch to using a token but my requests fail (401) Unauthorized.Error content: {"error":"invalid_token"

Am I missing something?

 Dim requester As New ZendeskApi_v2.Models.Tickets.Requester
        requester.Email = "john@doe.com"

        Dim zencomment As New ZendeskApi_v2.Models.Tickets.Comment
        zencomment.Body = "test comment"

        Dim ticket As New ZendeskApi_v2.Models.Tickets.Ticket
        ticket.Requester = requester
        ticket.Comment = zencomment
        ticket.Subject = "test subject"

        Dim zendesk As New ZendeskApi("https://help___.zendesk.com/api/v2", "TOKEN_STRING_HERE")
        zendesk.Tickets.CreateTicket(ticket)

**Comment by CKCobra** [comment]
Your example above will try to use an OAuthToken and I think you're trying to use an ApiToken.  Try the following:
`Dim zendesk As New ZendeskApi("https://help___.zendesk.com/api/v2", "USERNAME", Nothing, "APITOKEN_STRING_HERE", Nothing)`

**Comment by aliparlar** [comment]
Thank you for the pointer, it worked like this: 

Dim zendesk As New ZendeskApi("https://__help.zendesk.com/api/v2", "user@email.com", Nothing, "API_TOKEN_HERE", Nothing, Nothing)

**Comment by mozts2005** [comment]
issue has been fixed I am going to close
