### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by erossini** [mozts2005/ZendeskApi_v2#219]
Hi! I have a problem with the new project because when I created a new instance of `api = new ZendeskApi(endpoint, zendeskUsername, zendeskPassword);` I always received the following error:

> System.MissingMethodException: System.MissingMethodException: Method not found: 'Void ZendeskApi_v2.ZendeskApi..ctor(System.String, System.String, System.String)'..

Do you have any idea? Thank you in advance

**Comment by mozts2005** [comment]
Try deleting your nuget packages folder.  then run a full build.
