### ISSUE TITLE
Forum topics

### ISSUE THREAD

**Issue by devdept** [mozts2005/ZendeskApi_v2#221]
I used to get WebPortal forum topics this way:

api.Topics.GetTopicsByForum(forumIndex);

Now we switched to HelpCenter and it does not work anymore. What do I need to get the same list of topics from here?

https://devdept.zendesk.com/hc/en-us/community/topics/200619348-Announcements

Thanks.

**Comment by mozts2005** [comment]
I think what you want are the help desk articles. some example code for them can be find here. 

https://github.com/mozts2005/ZendeskApi_v2/blob/master/src/Tests/HelpCenter/ArticleTests.cs

**Comment by devdept** [comment]
Hi Elizabeth,

Is there a stable version support help center?

What about this constructor? Hi only have Url, user and password, where do I get apiToken, locale and p_OAuthToken?

public HelpCenterApi(string yourZendeskUrl, string user, string password, string apiToken, string locale, string p_OAuthToken)

Thanks,

Alberto

**Comment by devdept** [comment]
Please disregard my previous request, I downloaded the latest stable version and I don't need those extra parameters. 

Following your example, can you please show me how to get the list of topics on this forum? 

https://csharpapi.zendesk.com/hc/en-us/community/topics/200298245-Community-Help

**Comment by mozts2005** [comment]
the use if topics looks to be missing. Based on my read of the [zendesk api docs](https://developer.zendesk.com/rest_api/docs/help_center/topics)  we can added it. 

Would you like to try an add this via pull request as you will be using the api and will be able to better insure that it will complete the task you need it to ?

**Comment by devdept** [comment]
Hi Elizabeth,

Unfortunately I work in a totally different field and I am not familiar with CURL. Rest assured that I will test it immediately. I'm surprised to see that you don't cover something it was present in Web Portal. 

We need this feature (api.Topics.GetTopicsByForum(_forumIndex_)) to get latest posts in the community forums and display them on the Corporate website home page. Since the day we switched to HelpCenter our home page is broken.

Thanks.

**Comment by mozts2005** [comment]
I take a look and see what I can do but I will not be able to give you an eta. if you would be willing to email me with more detail about how this is used in your web site I can try to get a basic version working that should cover your needs.

**Comment by devdept** [comment]
I use it in this way, nothing complicated (still refers to Web Portal API, for HelpCenter is missing):

ZendeskApi api = new ZendeskApi("https://devdept.zendesk.com/api/v2", "username", "password");
                    
// Announcements
GetForumPosts(200619348, api, sortedList);

// GetForumPosts() implementation 
private static void GetForumPosts(int forumIndex, ZendeskApi api, SortedList<DateTime, Topic> sortedList)
{
                GroupTopicResponse gtr = api.Topics.GetTopicsByForum(forumIndex);

                IList<Topic> topicList = gtr.Topics;

                foreach (Topic entry in topicList)
                {
                    sortedList.Add(entry.UpdatedAt.Value.DateTime, entry);
                }
}

**Comment by devdept** [comment]
Hi Elizabeth,

I see you did some changes, thanks. I tested the code.

I can I get the list of topics for forum with ID 200298245? Do you still need to implement it?

https://csharpapi.zendesk.com/hc/en-us/community/topics/200298245-Community-Help

**Comment by mozts2005** [comment]
I have it where you can get the list of topics. I need to still add it so that you can get the post in that topic.

**Comment by devdept** [comment]
Thanks Elizabeth.

**Comment by devdept** [comment]
Hi Elizabeth,

Any news on this?

**Comment by mozts2005** [comment]
I just finished adding the post for the API. Let em know if this works for you.

**Comment by devdept** [comment]
Hi Elizabeth,

Regarding this:

https://csharpapi.zendesk.com/hc/en-us/community/topics/200298245-Community-Help

Are you able to query this:

`api.HelpCenter.Topics.GetTopics(200298245).Topics`

and get:

- ātrais kredīts internetā no 18 gadiem 
- atrais kredits ogre 
- atrie krediti ar sliktu vesturi 
- ātrie kredīti visu diennakti 
- atrie krediti bez darba vietas no 18 
- pavļuts ātrie kredīti  

I don't :-(

Thanks.

Alberto

**Comment by mozts2005** [comment]
I think you may have the wrong code. try this
` var posts = api.HelpCenter.Posts.GetPostsByTopicId(200298245).Posts`

**Comment by devdept** [comment]
It works!

How would you get from:

https://csharpapi.zendesk.com/hc/en-us/sections/202119686-My-Test-section

this list instead?

- My Test article 
- My Test article 
- My Test article 
- My Test article 
- My Test article 
- My Test article 
 
Thanks.

**Comment by mozts2005** [comment]
you would use 

var articles = api.HelpCenter.Articles.GetArticlesBySectionId(202119686).Articles;

**Comment by devdept** [comment]
You changes completely fulfill my requirements. Thanks a lot!
