### ISSUE TITLE
Issue with NuGet package

### ISSUE THREAD

**Issue by vachumakov** [mozts2005/ZendeskApi_v2#223]
I use your NuGet packet v 3.2.20  and face with bug which is describe in the [ticket 195](https://github.com/mozts2005/ZendeskApi_v2/issues/195). There is no bug in the repository, but it is in  the packet.
So I had to refuse nuget packet and clone your repository.

**Comment by mozts2005** [comment]
Please try the package on the prerelease myget feed. https://www.myget.org/F/zendeskapi_v2_prerelease/api/v3/index.json or https://www.myget.org/F/zendeskapi_v2_prerelease/api/v2

Let me know if that fixes the bug you are running into and I will try  final release in the next two weeks or so.

**Comment by mozts2005** [comment]
Hey not received feedback. closing
