### ISSUE TITLE
invalid token

### ISSUE THREAD

**Issue by tofutim** [mozts2005/ZendeskApi_v2#225]
Hi, when I use curl, my email address and the api token, it works. However using the following

            var api = new ZendeskApi("https://xxx.zendesk.com/api/v2", "m9...g5k");
            var response = api.Tickets.CreateTicket(new Ticket()
            {
                Requester = new Requester() { Email = email, Name = "name" },
                Subject = "feedback",
                Comment = new Comment() { Body = description },
                CustomFields = new List<CustomField> { new CustomField() { Id = 33530487, Value = sbExtraInfo.ToString() } },
                Via = new ZendeskApi_v2.Models.Shared.Via() { Channel = project }
            });
            
I get

The remote server returned an error: (401) Unauthorized.Error content: {"error":"invalid_token","error_description":"The access token provided is expired, revoked, malformed or invalid for other reasons."} 

I'm also guessing my url can be just xxx.zendesk.com but why does the token not work?

**Comment by tofutim** [comment]
I ghink I should be using this instead             var api = new ZendeskApi_v2.ZendeskApi("https://csharpapi.zendesk.com/api/v2", Settings.Email, "", Settings.ApiToken, "en-us", null);

**Comment by mozts2005** [comment]
looks as you answered the question if not please ask for help on [gitter](https://gitter.im/mozts2005/ZendeskApi_v2?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
