### ISSUE TITLE
get User related info

### ISSUE THREAD

**Issue by PedroMordeP** [mozts2005/ZendeskApi_v2#227]
Is not an issue but I didn't know where to ask this.

Is there a way to get the user related information?
https://developer.zendesk.com/rest_api/docs/core/users#user-related-information

If not, It's possible to create this method for the next update? Something like

       public IndividualUserResponse GetUserRelatedInfo(long id)
        {
            return GenericGet<IndividualUserResponse>(string.Format("users/{0}/related.json", id));
        }

Thank you

**Comment by M3LiNdRu** [comment]
If you don't mind, I can help over that.

I'll do a PR

**Comment by mozts2005** [comment]
@M3LiNdRu all yours

**Comment by M3LiNdRu** [comment]
PR created https://github.com/mozts2005/ZendeskApi_v2/pull/244

**Comment by mozts2005** [comment]
I was able to get everything worked out with the zendesk and have merged pr #244
