### ISSUE TITLE
GrooveApi

### ISSUE THREAD

**Issue by tofutim** [mozts2005/ZendeskApi_v2#228]
Just wanted to say that this repo is inspirational. Thanks for writing it! I'm thinking about writing a GrooveApi and following your template.

**Comment by tofutim** [comment]
I did have a question about your setup. When you are ready to switch to Is_Prerelease false how do you actually do it? I see $script_versionNumber.contains("-") but does something get changed in the GitVersionConfig for that to happen?

**Comment by tofutim** [comment]
Looks like you just push a tag for say 1.0.0 to Is_Prerelease false. But now I am seeing

Patching AssemblyInfo
Patching src\GrooveApi\Properties\AssemblyInfo.cs...Wrong version format for assembly patching: 1.0.0.build.4036233

this is probably better in gitter. Sorry in advance.

**Comment by mozts2005** [comment]
answered in gitter
