### ISSUE TITLE
Would it be possible to compile ZendeskApi_v2 against .NET Framework 4.0?

### ISSUE THREAD

**Issue by devdept** [mozts2005/ZendeskApi_v2#230]
Upgrading our website to .NET Framework 4.5 is impossible at this time. The reason is a ton of NuGet packages that don't interact with each other.

Would it be possible to compile ZendeskApi_v2 against .NET Framework 4.0?

Thanks.

Alberto

**Comment by devdept** [comment]
It took the whole morning but I managed to upgrade my ASP.NET MVC project to .NET 4.5

Please disregard this request.

**Comment by mozts2005** [comment]
side note that the API is compatible with .Net 4.0 and should work just fine
