### ISSUE TITLE
Bulk/Batch endpoint support

### ISSUE THREAD

**Issue by nickcoad** [mozts2005/ZendeskApi_v2#232]
Hi, first of all just wanted to say I really like this implementation and have been using it extensively. I was wondering however if you have any plans to add support for the bulk/batch endpoints Zendesk added to their API last year?

https://developer.zendesk.com/blog/from-100-requests-to-1-introducing-our-new-bulk-and-batch-apis

This would be a great feature if you plan on adding it. Otherwise if you're not too keen on tackling it personally, maybe I can put something together and submit it as a pull request for you to review?

**Comment by mozts2005** [comment]
@nickcoad If you want to add Bulk endpoints. Then the task is yours . Please make sure that any questions you have are logged here so that others can provide their input.

**Comment by mozts2005** [comment]
looks like this has been added see https://github.com/mozts2005/ZendeskApi_v2/blob/master/src/ZendeskApi_v2/Requests/Tickets.cs#L84

I am closing this issue if you would like to see this in other areas in the API please open a more specific issue.
