### ISSUE TITLE
.net core support?

### ISSUE THREAD

**Issue by agonzalezm** [mozts2005/ZendeskApi_v2#235]
does it support .net core or any plan to support it?

**Comment by mozts2005** [comment]
I am not sure if it will work at this time. But I am working on changing the projects to use the new .net core system so we don't have to have all the different projects for the different versions of the framework. 

I do not have an ETA for this being complete.

**Comment by StefanRKarlsson** [comment]
ETA on this? Do you need help?

**Comment by mozts2005** [comment]
@StefanRKarlsson I am working on it. I am hoping to have a very early alpha out late next week.

This will be a complete rewrite. So I will need your and others help with feedback to make the code usable and testable.

**Comment by Jetski5822** [comment]
Hey @mozts2005 whats the good word on this?

Is the code in Master dotnet core compliant ?

**Comment by ctolkien** [comment]
Jumping in one this issue too. Let us know where we can help.

**Comment by bmnielsen** [comment]
Same here, this is blocking us from moving to .Net Core. If there's anything we can do to help, please let us know.
