### ISSUE TITLE
SortOrder is ignored for search results

### ISSUE THREAD

**Issue by mbtyomkin** [mozts2005/ZendeskApi_v2#238]
Trying to use Search.SearchFor and passing "asc" as SortOrder (default on zendesk is desc - https://developer.zendesk.com/rest_api/docs/core/search), but the code seems to pass "desc" or nothing to the API. I assume that's because the default was "asc" before. Recommendation: do not assume the default and pass along the user's value. Perhaps introduce an enum for this value, so the user does not pass an invalid value (ex. "ascending").

**Comment by mozts2005** [comment]
@mbtyomkin  Please test this change to make sure I fixed your issue. You will need to use the myget feed for the pre-release version.
