### ISSUE TITLE
Update Ticket disregards public flag for comments

### ISSUE THREAD

**Issue by larsm11** [mozts2005/ZendeskApi_v2#239]
When using Ticket.UpdateTicket to add comments to existing tickets, all comments become public regardless of public= being set to true og false.

Sample code that produces a public comment in Zendesk:
`var updateResponse = api.Tickets.UpdateTicket(ticket, new Comment() { 
		Body = "This comment is added as an internal note, but last time it came in as a public one ", Public = false})`

**Comment by jvb93** [comment]
Are you using the latest commit? This was supposedly fixed in PR https://github.com/mozts2005/ZendeskApi_v2/pull/234

I'm testing now, will confirm in a bit.

**Comment by mozts2005** [comment]
@jvb93 let me know if this fix is working and I will make a prod release of it.

**Comment by jvb93** [comment]
@mozts2005 Well my simple test of creating a ticket with a private comment worked so that's a huge step in the right direction - looking forward to the next NuGet release.

**Comment by larsm11** [comment]
Yes, it works now. 

Thanks.

/LarsM
