### ISSUE TITLE
Ticket Group null

### ISSUE THREAD

**Issue by adamjsharpe** [mozts2005/ZendeskApi_v2#246]
When I use the Tickets.GetTicket() method, the ticket comes back but the groups are always NULL. How do I get a count of tickets assigned to a given group?

**Comment by mozts2005** [comment]
Can you supply a test case with example code?

**Comment by mozts2005** [comment]
I added a test case, please have a look at it and see if that show you what you are looking for.

Note that groups are more like security group, not categories.  I think what you want are called tags and I have shown how they work as well in my test case.
