### ISSUE TITLE
Comment channel changed from "api" to "web" when pusing to zendesk

### ISSUE THREAD

**Issue by alexandarsynergy** [mozts2005/ZendeskApi_v2#254]
I think that I’ve found an issue. It’s when we are pushing comments to Zendesk via Code, the comment channel is changed from “api” to “web”.

Tickets are created with ticket channel “api” which is correct, it’s just comments that make issues with “api” changing to “web”.

I'm using this call api.Tickets.UpdateTicket(ticketUpdate, comment);

the comments is crated like this:
Comment newcomment = new Comment();
newcomment.Body = lastentry.Title + " \r\n" + lastentry.Description.ToString() + " \r\n" + Notes;
newcomment.Via = new ZendeskApi_v2.Models.Shared.Via();
newcomment.Via.Channel = "api";

After pushing the comment to Zendesk the Chanel is "web"... Everything working correctly through the zendesk test console https://developer.zendesk.com/requests/new

**Comment by alexandarsynergy** [comment]
I think that I’ve found an issue. It’s when we are pushing comments to Zendesk via Code, the comment channel is changed from “api” to “web”. 

Tickets are created with ticket channel “api” which is correct, it’s just comments that make issues with “api” changing to “web”.

I'm using this call api.Tickets.UpdateTicket(ticketUpdate, comment);

the comments is crated like this:
 Comment newcomment = new Comment();
 newcomment.Body = lastentry.Title + " \r\n" + lastentry.Description.ToString() + " \r\n" + Notes;
newcomment.Via = new ZendeskApi_v2.Models.Shared.Via();
newcomment.Via.Channel = "api";

After pushing the comment to Zendesk the Chanel is "web"... Everything working correctly through the zendesk test console https://developer.zendesk.com/requests/new

**Comment by mozts2005** [comment]
I have looked at this. 
I am not seeing the issue you are please have a look at the test case I have created and let me know if somehow I have missed the issue you are having.

**Comment by mozts2005** [comment]
It Has been more than a week I am closing this issue
