### ISSUE TITLE
Problem updating custom Ticket Fields Async 

### ISSUE THREAD

**Issue by trosenfeld** [mozts2005/ZendeskApi_v2#256]
Hello,

Today I was trying to update a custom drop-down ticket field.
The request JSON isn't serializing properly.
It's currently being serialized as:
`{"custom_field_options" : [{"name" : "Option 1", "value" : "option_1"},{"name" : "Option 2", "value" : "option_2"}]}`
It should however be serialized as:
`{"ticket_field": {"custom_field_options" : [{"name" : "Option 1", "value" : "option_1"},{"name" : "Option 2", "value" : "option_2"}]}}`

As far as I can see the TicketField needs to be wrapped just as the response is. (See the [CURL Example](https://developer.zendesk.com/rest_api/docs/core/ticket_fields#updating-drop-down-field-options) on the ZenDesk Developer Portal)
Either the IndividualTicketFieldResponse class should be used or a IndividualTicketFieldRequest class should be made which would be identical to the IndividualTicketFieldResponse class.

Currently when executing the request I'm receiving the `X-Zendesk-API-Warn` header with the following header value:
`Removed restricted keys ["url", "created_at", "updated_at", "type", "title", "description", "position", "active", "required", "collapsed_for_agents", "title_in_portal", "visible_in_portal", "editable_in_portal", "required_in_portal", "custom_field_options"] from parameters according to whitelist`

**Comment by mozts2005** [comment]
I am not able to replicate your issue. I do have a test case for this that can be found [here](https://github.com/mozts2005/ZendeskApi_v2/blob/0716779368ee2c63eecb5d1fcd3a5224081c3a66/src/Tests/TicketTests.cs#L779)

If you are abele to create a test that can replicate your issue and submit it as a pull request I would me more than happy to troubleshoot the issue more.

**Comment by trosenfeld** [comment]
Hi,

As I'm not that experienced with Github so haven't been able to create a pull request.
If you however make a copy of the unit test you referenced and use the Async methods the unit test will fail.
It probably would have been handy if I had mentioned in my initial post that I'm using the Async methods.

**Comment by mozts2005** [comment]
@trosenfeld  I have looked at the code for UpdateTicketField and UpdateTicketFieldAsync. I can see the issue. 

I will get this fixed ASAP.

**Comment by mozts2005** [comment]
Please have a look at the myget feed. version 3.5.3-alpha3 has the needed fix. 

If you need help with myget we should be able to help. just ping me on gitter.
