### ISSUE TITLE
API.HelpCenter.Articles.GetByPageUrl incorrectly formats the request Uri

### ISSUE THREAD

**Issue by mbtyomkin** [mozts2005/ZendeskApi_v2#270]
When using the API.HelpCenter.Articles.GetByPageUrl method, despite the nextpage parameter being set correctly (taken from previous response), the Uri that the API builds is wrong. It is builds a Uri that points to the Core API, not the Help Center API.

**Comment by mozts2005** [comment]
@mbtyomkin  I am unable to replicate your issue. I have created a pull request with a test case that I added.

I you find that my test is not how you are using the method please submit an example test of your own
