### ISSUE TITLE
OrganizationMembership Default nullable binding

### ISSUE THREAD

**Issue by joplaal** [mozts2005/ZendeskApi_v2#277]
As is stated at https://developer.zendesk.com/rest_api/docs/core/organization_memberships, about the "default" property:
Denotes whether this is the default organization membership for the user. If false, returns null

So the OrganizationMembership Default property should be nullable. 

If not, the API raise a Json exception since a null value can not be binded to a not nullable property

**Comment by mozts2005** [comment]
I am not able to replicate this issue. Can you please have a look at this test and let me know what you are doing differently. 

https://github.com/mozts2005/ZendeskApi_v2/blob/master/src/Tests/OrganizationTests.cs#L121

If you would like to feel free to create a pull request will a failing test case.

**Comment by joplaal** [comment]
I try to reproduce it using modifiying some projects test but I have not been able to. Maybe it depends on the zendesk account configuration. Our account allows multiple organizations per user, maybe the one used in the tests is configured in a different way.

In fact, I was able to write a test that seems to fail when trying to add several organizations to the same user

**Comment by mozts2005** [comment]
based on my testing it looks like the Create Membership option deletes all otheTo create a user with more than one membership use the create many end-point.  When used option can be updated as well.
