### ISSUE TITLE
Thumbnail class exsists, but creation is not supported

### ISSUE THREAD

**Issue by nicolebrum** [mozts2005/ZendeskApi_v2#278]
What I want to do is set a thumbnail for the attachment, to display a thumbnail instead of the link with the name of the file. I see that there is a Thumbnail class, but I cannot set it to the Comment, Attachment or ZenFile classes. There should be a way to link Thumbnails to those classes.

**Comment by mozts2005** [comment]
based on my read of the API docs. I do not think this can be done. Thumbnails are created by zendesk when images are attached to other objects.  If you more info or an example please let me know.
