### ISSUE TITLE
How is attachments handled for the new HelpDesk Articles?

### ISSUE THREAD

**Issue by JonasMolgaard** [mozts2005/ZendeskApi_v2#280]
I was trying to add a document to an article today, and noticed that there's not an Attachments list exposed. I vaguely recall, that that was implemented differently for Topics (the old forum), so question is, if we also need to use "Attachments" and get the uploaded token for Articles?

**Comment by mozts2005** [comment]
You can now add attachments to articles now. please test using the [myget feed](https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2) release. Let me know if you have any issues. I will wait for your feedback before releasing 3.6.2

**Comment by JonasMolgaard** [comment]
Sorry for the missing feedback. I just pulled code today and as far as i can tell, i got 3.7.1.0 now and inspected the class Article, but can't see ArticleAttachments or Attachments, so i suppose something is missing or im looking the wrong place?

**Comment by JonasMolgaard** [comment]
Oh it's an api.HelpCenter.ArticleAttachments, and then i suppose i call UploadAttachment to that article with corresponding ZenFile.
