### ISSUE TITLE
"brand_id" property does not exist in Result object.

### ISSUE THREAD

**Issue by Ashatz** [mozts2005/ZendeskApi_v2#281]
I am currently using the Search functionality to pull tickets based upon values of a given custom field.  The client made a specific ask for the "brand_id" property to be present. However when I use the Search functionality, the "brand_id" property does not exist in the search Result object.  When using an Http listener like Fiddler, one can clearly see that the Zendesk Web API does return a "brand_id" property, but because it does not exist in the Results object, it is subsequently not deserialized.

I can work around this by using the ticket Ids from the Search and calling the GetMultipleTickets method in the Ticket service, however I feel that it is important to add this property, along with any additional missing properties to the object for additional clarity.

**Comment by mozts2005** [comment]
unable to recreate the issue please review the test case that I have created and let me know what steps I am missing. [Test Case](https://github.com/mozts2005/ZendeskApi_v2/blob/issue-281/src/Tests/TicketTests.cs#L1331)
