### ISSUE TITLE
Is_public missing in ticket object

### ISSUE THREAD

**Issue by dgirbal** [mozts2005/ZendeskApi_v2#283]
Hello, 

Thanks for you developpment, have you plan to add the field "is_public" in your next version 3.6.2?

best regards

**Comment by mozts2005** [comment]
I will get this added. As a workaround to can check the comments for the ticket.

**Comment by dgirbal** [comment]
Thks for your answer and the workaround. best regards

**Comment by mozts2005** [comment]
I have added the property please test using the myget feed and let us know if this works for you.
