### ISSUE TITLE
Getting a list of article titles without body

### ISSUE THREAD

**Issue by ScoobyDownUnder** [mozts2005/ZendeskApi_v2#287]
Just started using 3.6.1 of the API so I might be missing the appropriate method/approach:

When I call GetArticlesByCategoryId, I get back all those articles. However, I would ideally just want to get back the id and title, etc. so I can display a list to the user rather than the extra payload of the Body itself.

Is there are way to currently achieve this, or does this require an enhancement?

**Comment by overanalyzer** [comment]
@ScoobyDownUnder Unless I'm reading the Zendesk API docs wrong, it doesn't look like there's an endpoint that would give back just the id and title.

https://developer.zendesk.com/rest_api/docs/help_center/articles

**Comment by ScoobyDownUnder** [comment]
@overanalyzer Yeah, I could not see one, but given new to the API though I might be missing some approach to getting this via search, etc.
The Zendesk itself shows a list of article titles without the body, so they are doing this internally...I'll ask Zendesk direct!

**Comment by overanalyzer** [comment]
@ScoobyDownUnder Yeah, definitely a good question for Zendesk. 

You and I might be overlooking an endpoint looking at the docs, or they might have a non-public API endpoint they use for that (which you could push for them to add to the public API), or they might just ignore the extra data when presenting the list view (though that seems a bit odd to me, it'd potentially be a lot of extra data, which I'm sure is why you're wondering).

If you find something out, you could ask @mozts2005 about adjusting the library accordingly if they add something new, or it's missing something.

**Comment by mozts2005** [comment]
@ScoobyDownUnder Please let us know if you hear anything from zendesk.

**Comment by ScoobyDownUnder** [comment]
Zendesk confirm no way to do this ATM, and that Change Request needed. Personally, I'd prefer odata support so we can perform selects to get the fields we want and ignore those that we don't...
