### ISSUE TITLE
Error using GetTickets()?

### ISSUE THREAD

**Issue by tmenegh** [mozts2005/ZendeskApi_v2#288]
Hello, 
I've been using the API for quite some time now. I had an issue present itself on 7/4 around 5 A.M. The API is used within a webpage running on Windows Server 2003 with .NET Framework 4. I've verified communication with the server and zendesk via a cURL post but I'm still receive the error below.

The underlying connection was closed: An unexpected error occurred on a send.Error content:  
 Resource String: tickets/7774013.json  + 

The issue only occurs on the server. I am able to run it from my development machine without error. Any suggestions?

**Comment by mozts2005** [comment]
Without more information, I can be sure what your issue is. I have a few ideas. 

1. [Rate limit](
 https://developer.zendesk.com/rest_api/docs/core/introduction#rate-limits)
2. [TLS](https://developer.zendesk.com/rest_api/docs/core/introduction#security-and-authentication)

What version of the of the library are you using?
Can you share stack trace?

**Comment by wclarke99** [comment]
Hi @mozts2005 We are having the same issue, "The underlying connection was closed: An unexpected error occurred on a send". We have been running this code for 18 months without issue. file ZendeskApi_v2_35 Version 2.0.0.0

**Comment by tmenegh** [comment]
It appears to be an issue with TLS and .Net Framework 4. The issue was present when trying to run the Models.Ticket.GetTicket() function from a console application on the server. I was unable to complete any requests to our zendesk subdomain from the server using the RestSharp library written by John Sheehan as well. We have since moved to a new 2012 Web Server and all issues have been resolved.

Thank you for your time.

**Comment by mozts2005** [comment]
@wclarke99 I would like to help you more. Can you provide a stack trace? 

@tmenegh I am glad that you were able to fix the issue.

**Comment by wclarke99** [comment]
@mozts2005 Hi Elizabeth, below is the stack track - 
Stack trace:    at ZendeskApi_v2.Core.RunRequest(String resource, String requestMethod, Object body)
   at ZendeskApi_v2.Core.RunRequest[T](String resource, String requestMethod, Object body)
   at ZendeskApi_v2.Core.GenericGet[T](String resource)
   at ZendeskApi_v2.Requests.Tickets.GetTicketForms()
   at ZendeskAPIWrapper.GetTicketForms()
   at ServiceRequests_2.GenerateAddNewRequestSelections()
   at ServiceRequests_2.Page_Load(Object sender, EventArgs e)
   at System.Web.Util.CalliHelper.EventArgFunctionCaller(IntPtr fp, Object o, Object t, EventArgs e)
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by mozts2005** [comment]
@wclarke99  Based on my testing and I think your issue is TLS cipher suites.  I would use  [IISCrypto](https://www.nartac.com/Products/IISCrypto) to test which ones are supported on your server and by zendesk.

**Comment by mozts2005** [comment]
There has not been a reply in over a week. I am closing this issue

**Comment by seagulledge** [comment]
I had this same problem with an .Net 4.52 application.   The underlying network calls use TLS 1.0 as the default.  The fix was to add before the API call:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Note:   .Net 4.6 or higher uses TLS 1.2 as the default

**Comment by nicolebrum** [comment]
I also had this problem and @seagulledge 's solution has worked perfectly! Thank you :)

**Comment by ShriN** [comment]
Thanks @seagulledge! Your solution worked perfectly.

**Comment by QuentinDosSantos** [comment]
Thank you so much @seagulledge !
