### ISSUE TITLE
system_field_options missing

### ISSUE THREAD

**Issue by Firefox** [mozts2005/ZendeskApi_v2#290]
When you call the **ticket_fields** method  from the API by calling **api.Tickets.GetTicketFieldById(id)** it doesn't return a list of the *system_field_options*. 
Described here: https://developer.zendesk.com/rest_api/docs/core/ticket_fields

I have thoroughly studied the code and looked everywhere in the past issues but couldn't find anything relating to this. Is there a reason for this not being there?

**Comment by mozts2005** [comment]
I have added the missing property for system field options. Please test using the [myget feed](https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2) version.

**Comment by Firefox** [comment]
Done. 
Tested it by getting 3 separate system ticket fields (Type, Priority, Status). 
Returning results as expected. 
Thanks.
