### ISSUE TITLE
GetArticlesByCategoryIdAsync - missing locale

### ISSUE THREAD

**Issue by ScoobyDownUnder** [mozts2005/ZendeskApi_v2#291]
In the zendesk api, it has: /api/v2/help_center/{locale}/categories/{id}/articles.json

The current implementation of GetArticlesByCategoryIdAsync, does not allow the injection of locale in the call, so it can only be used by admins rather than end users...

Can you provide an extra parameter for this? Or feed off the constructor locale if there?

**Comment by mozts2005** [comment]
I have added this. please test using the [myget feed release 3.7.0-alpha1](https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2/3.7.0-alpha1)

Let us know how it works for you.

**Comment by ScoobyDownUnder** [comment]
Hi
Thanks for this. I'm currently getting 404 Not Found, but suspect that's more likely an actual Zendesk issue as our categories/sections/articles, etc. are a mix of en-GB, en, en-US...and we need to fix that to simply be en for all...

Looking at the code, presume I simply need to change my constructor, and then it uses the locale wherever appropriate:
var zendesk = new ZendeskApi(PlanetZendeskUrl, null, null, null, "en", oauthToken);
var articleResponse = await zendesk.HelpCenter.Articles.GetArticlesByCategoryIdAsync(DocumentCategoryId,
                ArticleSideLoadOptionsEnum.Sections).ConfigureAwait(false);

**Comment by mozts2005** [comment]
Yes, you would set the locale in the constructor. If you set it to null or empty it is left out to allow admin access paths to still work. I did some testing and can't get a 404.

I was thinking that maybe it would be better to query the current user's locale and use that if they are only an end-user?

**Comment by ScoobyDownUnder** [comment]
Well originally, we coded it to use the end user locale, so given we have en-AU, and en-US, these would have been passed.

However, I think the Zendesk guide takes those locales to explicitly filter the categories/articles, etc. so unless it matches exactly, you don't get a result.

So if are article is en-AU, the en-US won't get a result...but also, I don't think they fallback, so if marked en, and we request en-US, no result...

Hence I think we have to code the interaction all with 'en' and ensure everything in Zendesk itself is 'en'...

**Comment by mozts2005** [comment]
Gen that I will leave it as is for now.

**Comment by ScoobyDownUnder** [comment]
Yep, I'm sure there is no issue with your library code, and its configuration on zendesk itself.  Appreciate your rapid responses btw...and neat code...

I notice for v4 it will all be async: are you going to put in ConfigureAwait(false) on these calls?

I will get back on this thread when I've resolved it 100%...

**Comment by mozts2005** [comment]
Yes, I plan on calling ConfigureAwait(false).

**Comment by ScoobyDownUnder** [comment]
I can confirm this all works as expected.
