### ISSUE TITLE
Create ticket as a "follow up" ticket

### ISSUE THREAD

**Issue by ghostgraham** [mozts2005/ZendeskApi_v2#296]
This is an enhancement request. The Zendesk API allows you to create a ticket as a follow up ticket -  https://developer.zendesk.com/rest_api/docs/core/tickets#creating-follow-up-tickets - this is the only way to perform  any kind of update on an already closed ticket, which simply creates a link from the old ticket to the newly added follow up ticket. 

This isn't currently possible through the ZendeskAPI_v2 wrapper, but it looks like it only needs an extra field to be able to support this. You can already add a ticket.Via.Source.From.Rel = "follow_up" but it's not possible to add the Id of the ticket you are creating this as a follow up to (i.e. there's no ticket.Via.Source.From.Id attribute). 

Apologies if this isn't written very clearly - please let me know if I need to provide further information. This is not urgent but if quick/simple to implement would be very much appreciated to enable this functionality. Thanks.

**Comment by mozts2005** [comment]
please test https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2/3.7.1-alpha1.

**Comment by jslaybaugh** [comment]
Worked for me! Setting `ViaFollowupSourceId` to a closed ticket works as hoped.

**Comment by mozts2005** [comment]
Good,  I will Get the release out so that other can use this.

**Comment by ghostgraham** [comment]
This is perfect, works for me, thankyou so much for applying this, it is a huge help and the fast implementation is very much appreciated. Graham.

**Comment by jslaybaugh** [comment]
Any update on when 3.7.1 will be available on nuget.org? I think I'm running into some really hard-to-nail-down issues with deployment and having multiple package sources.
