### ISSUE TITLE
Creating a follow up ticket

### ISSUE THREAD

**Issue by jslaybaugh** [mozts2005/ZendeskApi_v2#297]
Maybe I'm just missing it, but I'm unable to find out how to create a follow up ticket as described in https://developer.zendesk.com/rest_api/docs/core/tickets#creating-follow-up-tickets.

Is there a way to set the `via_followup_source_id` property when calling `CreateTicket()`?

**Comment by mozts2005** [comment]
Please, see issue #296 for this issue.
 Closing as duplicate
