### ISSUE TITLE
GetArticlesBySectionId returns 0 results

### ISSUE THREAD

**Issue by JonasMolgaard** [mozts2005/ZendeskApi_v2#299]
I've checked with this: 
var section = api.HelpCenter.Sections.GetSectionById(206246128);

That i do indeed get a section for that id. After that, i've called the method:

var articles = api.HelpCenter.Articles.GetArticlesBySectionId(206246128);

This returns 0 articles. When i navigate to our helpcenter in a webbrowser, i can see 34 articles in that Section.

Additionally, when i call:
api.HelpCenter.Articles.CreateArticle(206246128, myArticle);
i can't seem to find it afterwards in the helpcenter in a webbrowser. However, The above query for articles, now returns 1, so somehow either, im doing something wrong or there's a bug in the api. Not sure which though. Let me know if you need further details.

**Comment by mozts2005** [comment]
I am unable to replicate this issue. Can you please create a unit test replication the issue and add it to a pull request?
