### ISSUE TITLE
Help Center Access Policies will be deprecated

### ISSUE THREAD

**Issue by theriama** [mozts2005/ZendeskApi_v2#302]
On June 26th, 2017, Zendesk Guide introduced User Segments and the User Segments API as a successor to the Help Center Access Policies API. Since that time the endpoint has been backward compatible, automatically converting Access Policies created with the old API into User Segments. On December 15, 2017 the Access Policies API will be deprecated and removed from the product. This will give users of the current Access Policies API an additional three months to switch to the new API.

Change   Date: December 15th, 2017

https://help.zendesk.com/hc/en-us/articles/115008572427--Sunsetting-Access-Policies-for-Help-Center

**Comment by jmprovencher** [comment]
#311 In review

**Comment by mozts2005** [comment]
I have fixed the unit test. Please get the latest release from the myget feed and test.

https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2/3.7.2-alpha5

Once I get the all clear I will create the release on the public nuget feed.
