### ISSUE TITLE
Create new Ticket

### ISSUE THREAD

**Issue by jasirsharif** [mozts2005/ZendeskApi_v2#309]
I have managed to set up a connection to my Zendesk account and retrieve tickets from my account and display these in my webpage. 

However, I am trying to create a new ticket. So far I have tried this approach:

![api_create](https://user-images.githubusercontent.com/32903729/31722839-6dfc6d72-b41d-11e7-96c6-5a642fb5599f.PNG)

But this gives me an error:

"WebException: The remote server returned an error: (422) Unprocessable Entity.
System.Net.HttpWebRequest.GetResponse()
WebException: The remote server returned an error: (422) Unprocessable Entity.Error content: {"error":"RecordInvalid","description":"Record validation errors","details":{"base":[{"description":"Description: cannot be blank","error":"BlankValue","ticket_field_id":32972409,"ticket_field_type":"FieldDescription"}]}} "

What am I doing wrong?

**Comment by mattnis** [comment]
What is the error message?

-Matt-

**Comment by mozts2005** [comment]
Please have a look at this test case https://github.com/mozts2005/ZendeskApi_v2/blob/master/test/ZendeskApi_v2.Test/TicketTests.cs#L493

Please note as well that you must have a comment every time you create a Ticket.

**Comment by jasirsharif** [comment]
Thank you so much!
