### ISSUE TITLE
Core.cs is less forgiving for parameter 'yourZendeskURL' than ZendeskApi.cs is

### ISSUE THREAD

**Issue by janvanderhaegen** [mozts2005/ZendeskApi_v2#312]
The ZendeskApi implementation can handle a variety of inputs for 'yourZendeskURL' and will transform the url.
For example,  "contoso", "contoso.zendesk.com", "http://contoso.zendesk.com" etc will all work, the input is transformed into "https://contoso.zendesk.com/api/v2/".

However, the Core base class (used as the base class for HelpCenterApi amongst others) is less forgiving, at a first glance it only adds the trailing slash but nothing else.

**Comment by mozts2005** [comment]
I am missing what the issue here is. What are you asking to be changed ?

**Comment by mozts2005** [comment]
Ok, Got it. That is not how it should be used at all. 
try following this https://github.com/mozts2005/ZendeskApi_v2/blob/master/test/ZendeskApi_v2.Test/HelpCenter/ArticleTests.cs
