### ISSUE TITLE
Dedicated method for user incremental export

### ISSUE THREAD

**Issue by djdavis2** [mozts2005/ZendeskApi_v2#315]
Hi,

Please provide dedicated method for user incremental export.

https://developer.zendesk.com/rest_api/docs/core/incremental_export#incremental-user-export

**Comment by fuhye** [comment]
I am using and custom versión i dont Knows why it feature was suppressed

**Comment by rwjdk** [comment]
I would like to make this one (should be fairly easy).

**Comment by rwjdk** [comment]
Added to source-code now
