### ISSUE TITLE
Request Class is missing Type 

### ISSUE THREAD

**Issue by jmuronis** [mozts2005/ZendeskApi_v2#317]
Documentation says you can include a Type, and my helpdesk requires it. 

type | string | no | no | The type of the request, "question", "incident", "problem", "task"

**Comment by mozts2005** [comment]
Can you give me the link to the doc page?

**Comment by jmuronis** [comment]
https://developer.zendesk.com/rest_api/docs/core/requests

**Comment by mozts2005** [comment]
please test

https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2
