### ISSUE TITLE
PlatfromNotSupportedException in UWP Windows 10 app in .NET Native compilation mode

### ISSUE THREAD

**Issue by AntonZhmyrov** [mozts2005/ZendeskApi_v2#322]
We have a UWP application for Windows 10, which targets the .NET Framework 4.6.1.
We have referenced your library via the NuGet package -> ZendeskApi_v2 (version 3.7.2).

When compiling the project in the .NET Native mode, we encounter a following issue:
Microsoft.Bcl.Async library can not be resolved, and the compiler spits out warnings saying, for example:

"ILTransform_0017: Assembly 'Microsoft.Threading.Tasks.Extensions' requests the address of the virtual method 'Stream.BeginWrite(byte[], int, int, AsyncCallback, object)' which is not available in the targeted .NET platform. Please ask the author of 'Microsoft.Threading.Tasks.Extensions' to provide an implementation that can be used in the currently targeted .NET platform."

Which leads to PlatfromNotSupportedException when trying to use, for example, the method ITickets.CreateTicketAsync(Ticket ticket).

In order to fix this issue, we cloned the repository, and rebuilt it as a class library for UWP Windows 10, targeting the .NET Framework 4.6.1. It all works fine in .NET Native as well as in not native modes.

As far as we can see, the best possible solution is to add another dll file into nuget package which targets at least .NET Framework 4.5 for UWP app, Windows 10. 

Is there any chance that you could implement this solution in the nearest future?
Or maybe you have another view to this problem?

**Comment by mozts2005** [comment]
Yes, this can be done and I will make it happen for the next release. Which I am hope to complete in the next week.

**Comment by AntonZhmyrov** [comment]
Thanks a lot! We are looking forward to it!

**Comment by mozts2005** [comment]
please test 

https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2

**Comment by AntonZhmyrov** [comment]
Thanks a lot! We tested the application and everything worked good. When do you think this version will be released and available via Nuget?
