### ISSUE TITLE
Remove Microsoft.Bcl dependency for .net45

### ISSUE THREAD

**Issue by vlad-kurdesov** [mozts2005/ZendeskApi_v2#329]
Hi there,

Could you please generate new package based on latest source?

I'm very interested in changes from pull request #328 because it would remove Microsoft.Bcl packages as 2nd level dependency (Microsoft.Net.Http 2.2.29 has dependency for these packages);

Thank you

**Comment by mozts2005** [comment]
the Microsoft.Bcl is required for the .net40  builds support async. I will look at fixing 4.5 to not need Microsoft.Bcl  But I have to have a system.net reference and I like having the most updated one not the GAC installed version.
