### ISSUE TITLE
Cannot set value for CustomField defined as drop-down type

### ISSUE THREAD

**Issue by ilCosmico** [mozts2005/ZendeskApi_v2#333]
Hello,

I need to create a ticket with a custom field set as drop-down, but I cannot figure out how to do it.

```
string fieldName = "Version"; // this field can have value 9, 10, 11
long id = 333; // the field id
string myVersion = "11"; // the value I want to set

// attempt1
CustomField cfVersion = new CustomField()
{
    Id = id,
    Value = myVersion
};

// attempt2
CustomField cfVersion = new CustomField()
{
    Id = id,
    Value = new CustomFieldOptions()
    {
        Id = id,
        Name = fieldName,
        Value = myVersion
    }
};
```

What am I missing?

**Comment by mozts2005** [comment]
Sorry, this took so long.

Have a look at this test case https://github.com/mozts2005/ZendeskApi_v2/blob/master/test/ZendeskApi_v2.Test/TicketTests.cs#L839

**Comment by ilCosmico** [comment]
I found the solution by myself. The right way was the "attempt1" by passing as value the tag used for the drop-box item.
