### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by yonahs** [mozts2005/ZendeskApi_v2#340]
I suddenly started getting this morning on a simple GetTicket call. I have not touched my code.
I am also going to try to contact zendesk to see if its their issue

`Exception Details: System.IO.IOException: Authentication failed because the remote party has closed the transport stream.`

**Comment by mozts2005** [comment]
Zendesk is only[ supporting TLS 1.2](https://support.zendesk.com/hc/en-us/articles/360000710347-Removal-of-support-for-TLS-protocol-versions-1-0-and-1-1) as of June 13, 2018

Options to fix this issue (in the order I would do them) 

1. update the project to just .NET 4.7.X
1.  add following code to your application this code will affect all HTTP calls.
This setting is global and may need to be different for other services. 
```Csharp
System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12 | System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls;
```
note:
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#support-for-tls-12

**Comment by yonahs** [comment]
I have done both of those things and it still does not work.
I have also noticed that I have other API services that I can not connect to.

What is interesting is that I can not open the link to my zendesk API in my browsers either.

So, I have come to understand that this has nothing to do with your wrapper, but can you offer any other advise?

**Comment by robinschrijer** [comment]
Hi Yonahs,  How are your TLS settings on your computer/server. Is TLS 1.2 enabled? what does this site say: https://www.ssllabs.com/ssltest/viewMyClient.html

**Comment by yonahs** [comment]
Thanks.
I solved it.
I had some settings in Fiddler messing me up.

**Comment by leonardomack** [comment]
I just added right before my call.
`System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12 | System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls;`

Works fine, but we need to understand other not releated API calls.
