### ISSUE TITLE
TLS/1.0 Error

### ISSUE THREAD

**Issue by ajomon** [mozts2005/ZendeskApi_v2#350]
I'm getting an error:

HTTPS handshake to soros.zendesk.com (for #14) failed. System.IO.IOException Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. < An existing connection was forcibly closed by the remote host 

I'm using an older version of the source code. How can can I fix this. Please advice. Thanks

**Comment by rwjdk** [comment]
Please see this one: https://github.com/mozts2005/ZendeskApi_v2/issues/339 (Pretty sure it is the same issue)
