### ISSUE TITLE
CreateRequest: Anonymous Requests 

### ISSUE THREAD

**Issue by wendellj** [mozts2005/ZendeskApi_v2#355]
I can't find a way to create an Anonymous Request in APIv2; the API documentation has this to say:

https://developer.zendesk.com/rest_api/docs/core/requests#create-request

When I use Postman to create a request (see below) this works:

https://swyfft.zendesk.com/api/v2/requests.json

{"request": {"requester": {"name": "Wendell Joost GMail", "email": "wendellj@gmail.com"}, "subject": "This is a test ticket", "comment": {"body": "This is a test ticket submitted via Postman." }}}

**Comment by mozts2005** [comment]
Have you tried https://github.com/mozts2005/ZendeskApi_v2/blob/9db4de982f179a92a1cb7045f6ae79f40a446d5a/src/ZendeskApi_v2/Requests/Requests.cs#L233 ?

**Comment by mozts2005** [comment]
closing this issue given that there has been no update.
