### ISSUE TITLE
Tickets.GetTicketsByViewID - int required, but must be long

### ISSUE THREAD

**Issue by bpapineau** [mozts2005/ZendeskApi_v2#357]
According to last ids from views of my Zendesk account (360004681868), the "int" format is becoming incorrect. It must be long, like GetTicketsByUserID and GetTicketsByOrganizationID .

Change
public GroupTicketResponse GetTicketsByViewID(int id);
into
public GroupTicketResponse GetTicketsByViewID(long id);

**Comment by bpapineau** [comment]
Edited.

**Comment by mozts2005** [comment]
I am unable to see the issue. based on this line I am calling this good. 

https://github.com/mozts2005/ZendeskApi_v2/blob/6e7602d4748aaa359b264e7e9fbfaba6ce960f07/src/ZendeskApi_v2/Requests/Tickets.cs#L54

please let me know what version you are using. 

If you are still having issues please give a link to the method in the code.

**Comment by bpapineau** [comment]
My bad, my version was old. You can delete this issue :(
