### ISSUE TITLE
Contact form ticket creation best practices

### ISSUE THREAD

**Issue by guylando** [mozts2005/ZendeskApi_v2#370]
We have a contact form and want it to generate a zendesk ticket which will include the message id, type, content and the user full name, email, phone, id.
Went over the examples in test cases files but they show all possible ways of calling requests and tickets apis. They dont explain what is THE BEST RECOMMENDED way of doing it.
So I have a couple of questions:

1)Should we use request api or tickets api?
2)Should we create a separate agent in zendesk used for the api or if we use a token we dont need it?
3)When authenticating to the api with a token, we should specify the user email or the agent email?
4)What is the recommended way to specify user language to support localization?
5)What is the recommended way to specify user phone?
6)What is the recommended way to specify user full name?
7)What is the recommended way to specify our contact message id? NOT TICKET ID
8)What is the recommended way to specify that ticket came from contact form channel?
9)What is the recommended way to specify contact message type?

Thanks

**Comment by mozts2005** [comment]
@guylando,

I would love to help, but I feel that these questions are more the preview of the Zendesk Team.  We add a layer of code to help you use their service.  We don't create the service. 

sorry, we could not help you.
