### ISSUE TITLE
Get Attachments From Ticket

### ISSUE THREAD

**Issue by FranckJ21** [mozts2005/ZendeskApi_v2#377]
Hello

We succeeded in attaching some files to a ticket

Now, we need a get these informations from another application. 

1. First, get the names of the attachments from a ticket to show / propose them

2. Second, download a specific attachment 

How can we do that ?

Best Regards
FranckJ21

**Comment by FranckJ21** [comment]
Hello, 

Can you help us for this problem ?

Best regards
FranckJ21

**Comment by mozts2005** [comment]
please have a look at 

https://github.com/mozts2005/ZendeskApi_v2/blob/0e45f4d58933b066b0b25f585b0b376c98547107/test/ZendeskApi_v2.Test/AttachmentTests.cs#L33-L67

If you need more info we will need an exmaple of what you are doing.

**Comment by FranckJ21** [comment]
Excuse me, i misspoke
Tickets already exist with the attachment

We want, to get back the tickets from ZenDesk with their attachment to show in an application the tickets concerning our customer with the names of the attachments and if need, download from zendesk to the customer's desktop one or several attachments.

Best regards

**Comment by mozts2005** [comment]
I am not sure why the example I gave has the steps of getting a ticket and its list of attachments see line 60 and then line 61 shows how to download it. 

please give and an example of the data missing for the provided example.

**Comment by FranckJ21** [comment]
We would like a form which give all the tickets (not closed) of a particular Customer

The tickets have been created a long time ago so we don't have a instance of IndividualTicketResponse
(no access to t1.Audit.Events.First())

We need these methods (in synchronous mode)

List<Ticket> = GetTicketsNonClosed(long OrganisationId) // Return the list of the ticket for a particular Customer

List<Attachment> = GetAttachmentsFromTicket(long TicketId) // Return the list of the attachments for a particular ticket (no download)

String DownloadAttachmentOnDisk(long AttachmentId, String FolderOnDisk) // return FolderOnDisk+FileName

Best regards

**Comment by mozts2005** [comment]
Please have a look at https://github.com/mozts2005/ZendeskApi_v2/tree/master/src/ZendeskApi_v2.Example. 

I have updated it to show you what would be needed for your work.

**Comment by FranckJ21** [comment]
Hi
What is ZendeskHelper ? And where can i find it ? (it is the only thing that prevent the compilation)

**Comment by FranckJ21** [comment]
Thanks, all work fine !
