### ISSUE TITLE
How to get search result part by part.

### ISSUE THREAD

**Issue by nkosyan** [mozts2005/ZendeskApi_v2#64]
Hi,

Its not a bug its a question:

I am trying to get search result part by part. In old version of the Zendesk I did it with the following way:

ZenDeskApi.ZenDeskApi _ApiObject;
SearchResults records = _ApiObject.GetSearchResults(query, page);

But I couldn't find the same functionality for the new version of the Zendesk. 
In the new version suggest is 100 items per page.
https://github.com/eneifert/ZendeskApi_v2#paging
But I want to get search result for example 30 items per page. How can I do it? Please help.

ZendeskApi_v2.ZendeskApi ApiObject;
SearchResults records = ApiObject.Search.SearchFor(query);

Thanks:

**Comment by Sachin4dotnet** [comment]
Hi eneifert ,

You should change the following code in ZendeskApi_v2/ZendeskApi_v2/Requests/Search.cs (line: 75)

<pre><code>
public SearchResults SearchFor(string searchTerm,  string sortBy = "", string sortOrder = "",int page=1)
        {
            var resource = string.Format("search.json?query={0}", searchTerm);

            if (page > 1)
            {
                resource += "&page=" + page;
            }

            if (!string.IsNullOrEmpty(sortBy))
                resource += "&sort_by=" + sortBy;

            if (!string.IsNullOrEmpty(sortOrder))
                resource += "&sort_order=" + sortOrder;
           

            return GenericGet<SearchResults>(resource);
        }
</code></pre>

to new code as below:
<pre><code>
public SearchResults SearchFor(string searchTerm,  string sortBy = "", string sortOrder = "",int page=1,int per_page=0)
        {
            var resource = string.Format("search.json?query={0}", searchTerm);

            if (page > 1)
            {
                resource += "&page=" + page;
            }

            if (per_page > 1)
            {
                resource += "&per_page=" + per_page;
            }

            if (!string.IsNullOrEmpty(sortBy))
                resource += "&sort_by=" + sortBy;

            if (!string.IsNullOrEmpty(sortOrder))
                resource += "&sort_order=" + sortOrder;
           

            return GenericGet<SearchResults>(resource);
        }
</code></pre>

I don't know GitHub much hence I am not able to change the code..
