### ISSUE TITLE
Could not load Newtonsoft.json

### ISSUE THREAD

**Issue by noodlescb** [mozts2005/ZendeskApi_v2#7]
Hi I am trying to implement some automatic zendesk ticket logging in a C# app using this implementation. 

I downloaded the package and added a reference to the net40/ZendeskApi_v2.dll . This is the code I placed, which is copy/pasted from your readme. 

ZendeskApi zd = new ZendeskApi("https://{mysite}.zendesk.com/api/v2", "myusername", "mypassword");

zd.Tickets.CreateTicket(new ZendeskApi_v2.Models.Tickets.Ticket() {
    Subject = "TestTicket",
    Description = "test description",
    Priority = TicketPriorities.Urgent
});

It compiles and seems to make sense but I am getting the following error: 
FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=4.5.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Do I need to have an explicit reference in my project to the json dll? What else could cause the error?

Thanks,
Caleb

**Comment by Jon-Blackburn** [comment]
I'm still getting this same error what exactly did you do with the dll to fix it?

**Comment by mozts2005** [comment]
What version of the ZendeskApi_v2 and Newtonsoft is in your bin directory?

**Comment by Jon-Blackburn** [comment]
3.6.2

**Comment by mozts2005** [comment]
@Jon-Blackburn  looks like an issue with the NuGet package. the 3.6.2 needs Newtonsoft.Json Version 10.0 but I list the 9.0.1 in the dependencies. Try install version 10. I will be doing a release this weekend I will make sure to think this with it.

**Comment by Jon-Blackburn** [comment]
Yeah I had installed the latest version of Newtonsoft.Json which was version 10.0.3.   This was the official error I was getting it was a File Load Exception:


{"Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"}

Thanks for your help.  I’ll look for the patch this weekend.

Thanks,
Jon
