### ISSUE TITLE
Tickets.GetMultipleTickets(Async) may fail for too many requested items

### ISSUE THREAD

**Issue by kendaleiv** [mozts2005/ZendeskApi_v2#72]
`Tickets.GetMultipleTickets(Async)` methods use an `HTTP GET`, which could result in an invalidly long url situation.

I haven't actually encountered this, but I suspect this could be a problem with too many tickets requested in one call.

One solution could be batching these requests, perhaps with parallelization.

**Comment by mozts2005** [comment]
Would Love to see a pull request.

**Comment by mozts2005** [comment]
based on the docs they limit the results to 100 at a time. 

https://developer.zendesk.com/rest_api/docs/core/tickets#show-multiple-tickets
