### ISSUE TITLE
Api.Users.GetAllUsers() Only Returns First 100 Users

### ISSUE THREAD

**Issue by toddca** [mozts2005/ZendeskApi_v2#98]
Calling the GetAllUsers method only returns first 100 users in Users collection of response even though the Count on the response is much higher. It would appear there is paging going on here within in the API and although there is a NextPage Uri I cannot find any way within this library to call the next page. eg I was expecting a GetAllUsers(int page = 1) where I could call GetAllUsers(2) to get the next page. Looking through the tests I don't see how you page through users in any of the methods that potentially return a large number of users.

**Comment by mozts2005** [comment]
Please Let Us know if you are still having issues or if there is anything we can still do to help.
